name: Build and Preview Workshop Docs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Makefile'

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-docs:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.8"
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build workshop site
        if: " github.event.action != 'closed' "
        run: |
          echo "GIT_PYTHON_REFRESH=quiet"
          make build-docs-website
      - name: Release preview to branch
        if: "! github.event.pull_request.head.repo.fork "
        uses: rossjrw/pr-preview-action@183082fd714654433c8e2f6daedbfb4f20f2a94a # v1.4.4
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
  publish-preview-docs:
    if: "! github.event.pull_request.head.repo.fork "
    name: Preview
    needs: preview-docs
    uses: ./.github/workflows/publish-docs.yml