name: Release Workshop Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Makefile'
  workflow_dispatch: {}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  release-docs:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.8"
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build workshop site
        run: |
          make build-docs-website
      - name: Release all docs to branch
        uses: JamesIves/github-pages-deploy-action@22a6ee251d6f13c6ab1ecb200d974f1a6feb1b8d # v4.4.2
        with:
          folder: ./dist
          branch: gh-pages
          clean-exclude: |
            pr-preview
            .github
  publish-docs:
    name: Publish
    needs: release-docs
    uses: ./.github/workflows/publish-docs.yml